apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-postgresql
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:9570bb47a3d8d2fe42f00f9b4d3a67f79b5fc4054de72d575283f18b0dc8f7c2
